---
title: "MYC overrides HIF-1α to regulate proliferating primary cell metabolism in hypoxia"

author:
- Courtney A. Copeland: 
    institute: bwh, hms
- Benjamin A. Olenchock: 
    institute: bwh, hms
- David R. Ziehr:
    institute: bwh, mgh, hms
- Sarah McGarrity: 
    institute: bwh, hms, ui
- Kevin Leahy: 
    institute: bwh, hms
- Jamey D. Young: 
    institute: vu
- Joseph Loscalzo: 
    institute: bwh, hms
- William M. Oldham:
    institute: bwh, hms
    correspondence: true
    email: woldham@bwh.harvard.edu
    
institute:
- bwh: Department of Medicine, Brigham and Women's Hospital, Boston, MA 02115, U.S.A.
- hms: Department of Medicine, Harvard Medical School, Boston, MA 02115, U.S.A.
- mgh: Department of Medicine, Massachusetts General Hospital, Boston, MA, 02114 U.S.A.
- ui: Center for Systems Biology, School of Health Sciences, University of Iceland, Reykjavik, Iceland
- vu: Departments of Chemical & Biomolecular Engineering and Molecular Physiology & Biophysics, Vanderbilt University, Nashville, TN 37240, U.S.A.

format:
  docx:
    reference-doc:  template.docx
    page-width: 7.5
    output-file: copeland_2023_flux_manuscript.docx
    
bibliography: 
- library.json
- pkgs.bib
csl: elife.csl

filters:
    - scholarly-metadata.lua
    - author-info-blocks.lua
---

```{r}
#| label: setup
#| include: false


```

\newpage

# Abstract 

Hypoxia requires metabolic adaptations to sustain energetically demanding cellular activities. While the metabolic consequences of hypoxia have been studied extensively in cancer cell models, comparatively little is known about the metabolic response of primary cells to hypoxia. We performed metabolic flux analyses of proliferating human lung fibroblasts and pulmonary artery smooth muscle cells in hypoxia. Unexpectedly, hypoxia decreased glycolytic flux despite activation of hypoxia-inducible factor (HIF) and increased glycolytic enzyme expression. Pharmacologic activation of HIF with the prolyl hydroxylase (PHD) inhibitor molidustat in normoxia did increase glycolytic flux, but hypoxia abrogated this effect. Multi-omic profiling revealed distinct molecular responses to hypoxia and pharmacologic PHD inhibition and suggested a critical role for MYC in modulating the HIF response in hypoxia. MYC knockdown in hypoxia increased lactate efflux, while MYC overexpression in normoxia blunted the effects of molidustat treatment. Together, these data suggest that other factors, notably MYC, supersede the anticipated effects of HIF-dependent up-regulation of glycolytic gene expression on glycolytic flux in hypoxic proliferating primary cells.

# Keywords

hypoxia / metabolic flux analysis / hypoxia-inducible factor / prolyl hydroxylase / MYC

\newpage

# Introduction

Cellular responses to hypoxia propel many physiologic and pathologic processes from wound healing and angiogenesis to vascular remodeling and fibrosis [@semenza2012b; @lee2019]. These activities require cells to continue energetically demanding tasks, such as macromolecular biosynthesis and proliferation, despite limited oxygen availability. Since respiration is the most efficient way for cells to produce energy, cell metabolism must adapt to meet energetic needs when oxygen supply is limiting. Understanding how these metabolic adaptations sustain critical cellular processes in hypoxia is fundamentally important to our understanding of human health and disease. 

\newpage 

# References

::: {#refs}
:::
