---
title: "Biomass"
date-modified: today
format: html
excecute:
  message: false
---

```{r}
#| label: setup
#| output: false

devtools::load_all()
suppressPackageStartupMessages({
  library(tidyverse)
  library(wmo)
  library(targets)
})

here::i_am("analysis/biomass.qmd")

theme_set(theme_wmo())
```

```{r}
#| label: data

withr::with_dir(here::here(), {
  biomass_clean <- tar_read(biomass_clean)
  biomass <- tar_read(biomass)
  biomass_equations <- tar_read(biomass_equations)
})
```

# Overview

Contributions to cellular biomass were estimated from cell dry weight and previously estimated compositions.

# Data

```{r}
#| label: plot

ggplot(biomass_clean) + 
  aes(x = as.factor(date), y = cell_mass) +
  facet_grid(~toupper(cell_type), scales = "free_x", space = "free_x") +
  geom_point(alpha = 0.5) +
  stat_summary(
    fun.data = "mean_se", 
    geom = "pointrange", 
    color = "red", 
    alpha = 0.8
  ) +
  labs(
    x = "Date", 
    y = "Cell mass (pg)"
  )
```

```{r}
#| label: biomass

gt::gt(biomass) |> 
  gt::cols_label(
    cell_type = "Cell Type", 
    biomass = "Biomass (pg/cell)"
  ) |> 
  gt::fmt_number(columns = biomass, decimals = 0) |> 
  gt::cols_width(
    cell_type ~ gt::px(100), 
    biomass ~ gt::px(200)
  ) |> 
  gt::opt_all_caps()
```

The biomass equations are:

```{r}
#| label: equations

biomass_equations |> 
  select(cell_type, eq) |> 
  gt::gt() |> 
  gt::cols_align("left") |> 
  gt::cols_label(
    cell_type = "Cell Type", 
    eq = "Equation"
  ) |> 
  gt::cols_width(
    cell_type ~ gt::px(100), 
    eq ~ gt::px(750)
  ) |> 
  gt::opt_all_caps()
```



